name: generate-manifest
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'prod'
    paths:
      - 'manifest.json'


jobs:
  deploy-qrgamestudio-com:
    runs-on: ubuntu-latest
    env:
      DEPLOY_SSH_KEY: ${{ secrets.WEB_QRGAMES_COM_DEPLOY_SSH_KEY }}
    steps:
      - run: mkdir src
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          path: 'src'
      - name: run deploy
        shell: bash
        run: |
          eval `ssh-agent -s`
          echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add - &&
          git clone git@github.com:QRGameStudio/web-qrgamestudio-com.git &&
          cp "src/manifest.json" "web-qrgamestudio-com/src/lib/manifest.json"
          git config --global user.email "git@qrgamestudio.com" &&
          git config --global user.name "QR Bot" &&
          cd web-qrgamestudio-com/src/lib/ &&
          git diff --exit-code || { echo "Nothing to do"; exit 0 } &&
          git add manifest.json &&
          git commit -m "chore: automatic manifest update" &&
          git push
